[package]
name = "fcpe-mlxrs"
version = "0.1.0"
edition = "2024"

[dependencies]
mlx-rs = { git = "https://github.com/blossom-slopware/mlx-rs.git", rev = "b9a843246bc494da02d680835e6c29c1056835b0", features = [
    "accelerate",
    "metal",
] }
anyhow = "1.0"
hound = "3.5"
safetensors = "0.7.0"
metal = "0.33.0"
ndarray = "0.17.2"

[[example]]
name = "infer"
path = "examples/infer.rs"

[dev-dependencies]
rubato = "2.0.0"
